# Permalinks
permalink:           none

# Setup
title:               10M DevSquad
tagline:             Code and more
paginate:            1
baseurl:             "/devsquad"

pages_list:
   About: '/devsquad/about'
   Feed: '/devsquad/atom.xml'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              The 10M team
  url:               https://twitter.com/nifty10m
  email:             info@10m.de

# Custom vars
version:             2.0.0
github:
  repo:              https://nifty10m.github.io/devsquad/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
