# Permalinks
permalink:           pretty

# Setup
title:               The 10M devsquad homepage
tagline:             The Jekyll Butler
paginate:            1
baseurl:             "/devsquad"

pages_list:
   About: '/devsquad/about'
   Archive: '/devsquad/archive'
   Feed: '/devsquad/atom.xml'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://nifty10m.github.io/devsquad/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

